services:
  - type: web
    name: tarfixer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PORT
        value: 5000
